In [1]:
print("Hello")

Hello

In [6]:
from pathlib import Path
import requests


def download_one_file_of_raw_data(year: int, month: int) -> Path:
    URL = f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month:02d}.parquet"
    
    response = requests.get(URL)

    if response.status_code == 200:
        path = f"./data/raw/rides_{year}-{month:02d}.parquet"
        
        open(path, "wb").write(response.content)
        
        return path
    else:
        raise Exception(f"{URL} is not available")

In [7]:
download_one_file_of_raw_data(2023, 1)

FileNotFoundError: [Errno 2] No such file or directory: './data/raw/rides_2023-01.parquet'

In [8]:
from pathlib import Path

list(Path("../data/raw").glob("*"))

[]

In [9]:
from pathlib import Path

Path("../data/raw").exists()

False

In [17]:
from pathlib import Path
import requests

def download_one_file_of_raw_data(year: int, month: int):
    url = f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month:02d}.parquet"

    response = requests.get(url)

    if response.status_code == 200:
        path = Path("../data/raw/rides_{:04d}-{:02d}.parquet".format(year, month))

        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "wb") as f:
            f.write(response.content)

        print(f"Saved at: {path}")
    else:
        print("Download failed")

In [18]:
download_one_file_of_raw_data(2023, 1)

Saved at: ..\data\raw\rides_2023-01.parquet

In [19]:
from pathlib import Path

list(Path("../data/raw").glob("*"))

[WindowsPath('../data/raw/rides_2023-01.parquet')]

In [2]:
import pandas as pd

df = pd.read_parquet("../data/raw/rides_2023-01.parquet")
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [5]:
import pandas as pd

In [2]:
!pip install pandas pyarrow
!pip install pandas

Requirement already satisfied: pandas in c:\users\immad\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: pyarrow in c:\users\immad\anaconda3\lib\site-packages (21.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\immad\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pandas in c:\users\immad\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\immad\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\immad\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

df = pd.read_parquet("../data/raw/rides_2023-01.parquet")
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [7]:
import sys
print(sys.executable)

C:\Users\immad\anaconda3\envs\taxi-demand-env\python.exe

In [5]:
import sys
!{sys.executable} -m pip install pandas pyarrow

Requirement already satisfied: pandas in C:\Users\immad\anaconda3\envs\taxi-demand-env\Lib\site-packages (3.0.2)
Requirement already satisfied: pyarrow in C:\Users\immad\anaconda3\envs\taxi-demand-env\Lib\site-packages (23.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\immad\anaconda3\envs\taxi-demand-env\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\immad\anaconda3\envs\taxi-demand-env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\immad\anaconda3\envs\taxi-demand-env\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\immad\anaconda3\envs\taxi-demand-env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
import pandas as pd

df = pd.read_parquet("../data/raw/rides_2023-01.parquet")
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [9]:
df = df[["tpep_pickup_datetime","PULocationID"]]

In [11]:
df.rename(
    columns={
        'tpep_pickup_datetime': 'pickup_datetime',
        'PULocationID': 'user_location_id'
    },
    inplace=True
)

df.head()

      pickup_datetime  user_location_id
0 2023-01-01 00:32:10               161
1 2023-01-01 00:55:08                43
2 2023-01-01 00:25:04                48
3 2023-01-01 00:03:48               138
4 2023-01-01 00:10:29               107

In [13]:
df.head()

      pickup_datetime  user_location_id
0 2023-01-01 00:32:10               161
1 2023-01-01 00:55:08                43
2 2023-01-01 00:25:04                48
3 2023-01-01 00:03:48               138
4 2023-01-01 00:10:29               107

In [22]:
df = df[
    (df["pickup_datetime"] >= "2023-01-01") &
    (df["pickup_datetime"] < "2023-02-01")
]

In [23]:
df["pickup_datetime"].min(), df["pickup_datetime"].max()

(Timestamp('2023-01-01 00:00:00'), Timestamp('2023-01-31 23:59:59'))

In [24]:
df.to_parquet('../data/second/validated_rides_2023_01.parquet')

OSError: Cannot save file into a non-existent directory: '..\data\second'

In [ ]:
df.to_parquet('../data/second/validated_rides_2023_01.parquet')